# fly.toml app configuration file generated for late-resonance-22 on 2023-07-07T12:13:50-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

[env]
  PORT = "8080" # add this

[experimental]
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8080 
  processes = ["app"]
